name: Algorithms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run an individual test for each data structure and each algorithm
jobs:
  algorithms_test:
    runs-on: ubuntu-latest
    env:
      COMMON_FLAGS: "-I./include -L./lib -lm -std=c++23"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run APSP Test
        run: |
          g++ -o apsp_tester tests/apsp_test.cpp $COMMON_FLAGS
          ./apsp_tester

      - name: Build and Run Fibonacci Test
        run: |
          g++ -o fib_tester tests/fib_test.cpp $COMMON_FLAGS
          ./fib_tester

      - name: Build and Run Knapsack Test
        run: |
          g++ -o knapsack_tester tests/knapsack_test.cpp $COMMON_FLAGS
          ./knapsack_tester

      - name: Build and Run LCS Test
        run: |
          g++ -o lcs_tester tests/lcs_test.cpp $COMMON_FLAGS
          ./lcs_tester

      - name: Build and Run Matrix Chain Test
        run: |
          g++ -o matrix_chain_tester tests/matrix_chain_test.cpp $COMMON_FLAGS
          ./matrix_chain_tester

      - name: Build and Run World Series Test
        run: |
          g++ -o world_series_tester tests/world_series_test.cpp $COMMON_FLAGS
          ./world_series_tester
