name: Algorithms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run an individual test for each data structure and each algorithm
jobs:
  apsp-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run APSP Test
        run: |
          g++ -o apsp_tester tests/apsp_test.cpp -I./include -L./lib -lm
          ./apsp_tester
    
  fib-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Fibonacci Test
        run: |
          g++ -o fib_tester tests/fib_test.cpp -I./include -L./lib -lm
          ./fib_tester
  
  knapsack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Knapsack Test
        run: |
          g++ -o knapsack_tester tests/knapsack_test.cpp -I./include -L./lib -lm
          ./knapsack_tester

  lcs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run LCS Test
        run: |
          g++ -o lcs_tester tests/lcs_test.cpp -I./include -L./lib -lm
          ./lcs_tester
    
  matrix-chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Matrix Chain Test
        run: |
          g++ -o matrix_chain_tester tests/matrix_chain_test.cpp -I./include -L./lib -lm
          ./matrix_chain_tester

  world-series-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run World Series Test
        run: |
          g++ -o world_series_tester tests/world_series_test.cpp -I./include -L./lib -lm
          ./world_series_tester
